# Generated by Django 6.0.4 on 2026-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('', '—'), ('F', 'Femme'), ('M', 'Homme'), ('A', 'Autre')], default='', max_length=1, verbose_name='Genre'),
        ),
    ]
