# Generated by Django 5 — champ texte italique sous le nom (landing équipe)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="qualification_display",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Ligne sous le nom",
            ),
        ),
    ]
