# Generated by Django 6.0.4 on 2026-05-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medecin_secretaire_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='qualification_display',
            field=models.CharField(blank=True, help_text="Texte court en italique sous le nom sur l'accueil (ex. « Cardiologue — Spécialiste en… »). Vide = la spécialité est réutilisée.", max_length=300, verbose_name='Ligne sous le nom'),
        ),
    ]
