# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_ecg_analyse"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretaire",
            name="salaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rémunération mensuelle (optionnel).",
                max_digits=12,
                null=True,
                verbose_name="Salaire",
            ),
        ),
    ]
