# Generated by Django 6.0.4 on 2026-05-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_secretaire_salaire'),
        ('appointments', '0004_alter_rendezvous_cree_par'),
        ('patients', '0003_patient_cin'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bilan_biologique', "Demande d'analyses / bilan biologique"), ('demande_examens', "Demande d'examens"), ('certificat', 'Certificat médical')], max_length=32)),
                ('certificat_type', models.CharField(blank=True, help_text='Code du type de certificat si kind=certificat.', max_length=40)),
                ('items', models.JSONField(blank=True, default=list, help_text='Liste de clés (analyses ou examens cochés).')),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_medicaux_delivres', to='accounts.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_medicaux', to='patients.patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_medicaux', to='appointments.rendezvous')),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'ordering': ['-date_creation'],
            },
        ),
    ]
