# Generated by Django 6.0.4 on 2026-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_documentmedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedical',
            name='certificat_data',
            field=models.JSONField(blank=True, default=dict, help_text='Mentions, finalités, lieu, n° dossier (certificats cardiologie).'),
        ),
    ]
