# Generated by Django 6.0.4 on 2026-04-25 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('signalee_par', models.CharField(choices=[('medecin', 'Médecin'), ('secretaire', 'Secrétaire')], default='secretaire', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounts.medecin')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_absence'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('rdv', 'Rendez-vous'), ('absence', 'Absence'), ('ordonnance', 'Ordonnance'), ('cabinet', 'Cabinet')], default='rdv', max_length=20)),
                ('destinataire_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('destinataire_secretaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.secretaire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCardiovasculaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('cholesterol_total', models.FloatField()),
                ('hdl', models.FloatField()),
                ('tension_systolique', models.PositiveSmallIntegerField()),
                ('traitement_hta', models.BooleanField(default=False)),
                ('tabagisme', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('score_points', models.IntegerField(default=0)),
                ('risk_percent', models.FloatField()),
                ('niveau', models.CharField(choices=[('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé')], max_length=10)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_cardio', to='accounts.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_cardio', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Score cardiovasculaire',
                'verbose_name_plural': 'Scores cardiovasculaires',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='StatutCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('fermé', 'Fermé')], default='ouvert', max_length=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_statut_cabinet', to='accounts.secretaire')),
            ],
            options={
                'verbose_name': 'Statut du cabinet',
                'verbose_name_plural': 'Statut du cabinet',
            },
        ),
    ]
