# Generated by Django 6.0.4 on 2026-05-15 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ecg_analyse'),
        ('cabinet', '0001_initial'),
        ('patients', '0003_patient_cin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.CharField(default='mitdb', help_text='Identifiant PhysioNet (ex. mitdb).', max_length=40)),
                ('record_id', models.CharField(help_text='Ex. 100, 208…', max_length=20)),
                ('fs', models.FloatField(default=360)),
                ('duree_s', models.FloatField(default=0)),
                ('risk_percent', models.FloatField(help_text='Indice % affiché (peut combiner ECG + dernier Framingham patient).')),
                ('niveau', models.CharField(choices=[('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé')], max_length=10)),
                ('risk_ecg_seul', models.FloatField(default=0, help_text='Indice dérivé uniquement du signal / annotations.')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('beat_counts', models.JSONField(blank=True, default=dict)),
                ('waveform', models.JSONField(blank=True, default=list, help_text='Échantillons ECG sous-échantillonnés pour affichage.')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_ecg', to='accounts.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_ecg', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Analyse ECG',
                'verbose_name_plural': 'Analyses ECG',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
