# Generated by Django 6.0.4 on 2026-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_repair_guest_columns_mysql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='cree_par',
            field=models.CharField(choices=[('patient', 'Patient'), ('visiteur', 'Visiteur (site public)'), ('secretaire', 'Secrétaire')], default='patient', max_length=20),
        ),
    ]
